name: Build DeskFlow on Debian 12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Can use 'debian-12' when it's available, currently using Ubuntu as the base

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment for building DeskFlow
        run: |
          # Update and install dependencies
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            git \
            pkg-config \
            qtbase5-dev \
            qtchooser \
            qtbase5-dev-tools \
            qt5-qmake \
            libboost-all-dev \
            libssl-dev \
            libsdl2-dev \
            libjpeg-dev \
            libpng-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libfreetype6-dev

      - name: Clone DeskFlow repository with submodules
        run: |
          git clone --recurse-submodules https://github.com/deskflow/deskflow.git
          cd deskflow

      - name: Build DeskFlow
        run: |
          cd deskflow
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)  # Use all available cores for faster build

      - name: Run tests (optional, if DeskFlow has tests)
        run: |
          cd deskflow/build
          make test # Optional step if tests are part of the build process

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: deskflow-build
          path: deskflow/build/
